name: Example Workflow

on:
  workflow_dispatch:
    inputs: {}

jobs:
  check_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update packages
        run: |
          #!/bin/sh

          set -e

          echo "Update packages"
