name: CI Pipeline

on:
  push: {}

  workflow_dispatch:
    inputs:
      jira-key:
        description: 'Jira key'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prd
      service:
        description: 'Service name'
        required: true
        type: string
      tag:
        description: 'Deployment tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
